// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugchbdmobxjrjdnrubfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnY2hiZG1vYnhqcmpkbnJ1YmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTcwNjgsImV4cCI6MjA2NjIzMzA2OH0.fcPWb_Yd_cLBf6C8TPsAWz0-MXU7352icLo5sG-Wnco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);